### ISSUE TITLE
entrée de jeu gratuit érronée

### ISSUE THREAD

**Issue by Alsageek67** [fbrossar25/Free-Games-Bot#3]
des jeux sont publiés en doublons, alors qu'ils ne sont plus gratuit (hélas)
![image](https://user-images.githubusercontent.com/2794898/115051916-9df56c00-9edd-11eb-9adf-aab5491c16fb.png)

**Comment by fbrossar25** [comment]
Effectivement, problème persistant au ré-affichage, jeux en double avec la semaine passé, je tente un reboot du bot

**Comment by fbrossar25** [comment]
Le reboot ne règle pas le bug, je vais investiguer.

**Comment by fbrossar25** [comment]
Fixed in 1.1.6
